-- CREATE DATABASE IF NOT EXISTS escola;
-- USE escola;

-- CREATE TABLE IF NOT EXISTS aluno (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(50) NOT NULL,
--     email VARCHAR(100) UNIQUE NOT NULL
-- );